### ISSUE TITLE
303 code license?

### ISSUE THREAD

**Issue by jclounge** [a1k0n/303#1]
Hello Andy, sorry I don't know how else to contact you with my question so I'm just creating this 'issue' here.
Is it permitted to use your nice sounding 303 code in a closed source commercial product?
Cheers, Jules

**Comment by a1k0n** [comment]
Hmm, I hadn't thought about it. I usually MIT-license stuff like this, so yes, you may use it in your product. It doesn't support accent/slide FWIW.

**Comment by jclounge** [comment]
Brilliant, thank you so much! It already sounds pretty cool even without accent/slide, but the main thing I'm looking for is the filter code currently anyway. Should I include a credit/thanks or license text or something?

**Comment by a1k0n** [comment]
Credit/thanks is good, no license text.

**Comment by jclounge** [comment]
Awesome, will do!
